

> Import libraries to use



In [1]:
import numpy as np

>  # Introduction to numpy (Skip if you already are familiar)

>> Creating a 1D array

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


>> Creating a 2D array


In [3]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


>> Creating an array full of zeros


In [4]:
a = np.zeros(shape=(10))
print(a)
a = np.zeros(shape=(5,2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


>> Infinity in numpy

In [5]:
print(np.inf)

inf


>> Max and Argmax

In [6]:
a = np.array([2,1,4,3])
print(np.max(a))
print(np.argmax(a))

4
2


>> From list to Numpy

In [7]:
l = [1,2,3,4]
print(l)
print(np.asarray(l))

[1, 2, 3, 4]
[1 2 3 4]


>> Random in numpy

In [8]:
# Array of Random integers ranging from 1 to 10 (with any size you want)
a = np.random.randint(low=1, high=10, size=(5,2))
print(a)

# Array of random elements of a list with any size you want
a = np.random.choice([0,1,2], size=(2,))

[[4 9]
 [3 7]
 [8 5]
 [1 2]
 [8 5]]


>> Shapes in numpy

In [9]:
a = np.random.randint(low=1, high=5, size=(4,2))
print(a.shape)
print(a)

# Reshape a to a vector of shape = (8,1)
a = a.reshape((8,1))
print(a.shape)
print(a)

(4, 2)
[[3 1]
 [2 4]
 [4 3]
 [3 3]]
(8, 1)
[[3]
 [1]
 [2]
 [4]
 [4]
 [3]
 [3]
 [3]]


# Pre-defined utilities

In [10]:

int_to_char = {
    0 : 'u',
    1 : 'r',
    2 : 'd',
    3 : 'l'
}

policy_one_step_look_ahead = {
    0 : [-1,0],
    1 : [0,1],
    2 : [1,0],
    3 : [0,-1]
}

def policy_int_to_char(pi,n):

    pi_char = ['']

    for i in range(n):
        for j in range(n):

            if i == 0 and j == 0 or i == n-1 and j == n-1:

                continue

            pi_char.append(int_to_char[pi[i,j]])

    pi_char.append('')

    return np.asarray(pi_char).reshape(n,n)

# 1- Policy evaluation

In [11]:
def policy_evaluation(n, pi, v, Gamma, threshhold):
    """
    This function should return the value function that follows the policy pi.
    Use the stopping criteria given in the problem statement.
    
    Parameters:
    n: The size of the grid or state space.
    pi: The policy to be evaluated.
    v: The current value function.
    Gamma: The discount factor.
    threshold: The threshold for the stopping criteria.
    """
    while True:
        v_old = v.copy()
        for i in range(n):
            for j in range(n):
                action = pi[i, j]
                next_state = (i + policy_one_step_look_ahead[action][0], j + policy_one_step_look_ahead[action][1])
                if 0 <= next_state[0] < n and 0 <= next_state[1] < n:
                    v[i, j] = -1 + Gamma * v_old[next_state[0], next_state[1]]
                else:
                    v[i, j] = -1
        max_diff = np.max(np.abs(v - v_old))
        if max_diff <= threshhold:
            break
    return v

# 2- Policy improvement

In [12]:
def policy_improvement(n,pi,v,Gamma):
  """
    This function should return the new policy by acting in a greedy manner.
    The function should return as well a flag indicating if the output policy
    is the same as the input policy.

    Example:
      return new_pi, True if new_pi = pi for all states
      else return new_pi, False
  """
  new_pi = np.zeros_like(pi)
  policy_stable = True

  for i in range(n):
    for j in range(n):
        old_action = pi[i, j]
        action_values = []

        for action in range(4):
            next_state = (i + policy_one_step_look_ahead[action][0], j + policy_one_step_look_ahead[action][1])
            if 0 <= next_state[0] < n and 0 <= next_state[1] < n:
                action_value = -1 + Gamma * v[next_state[0], next_state[1]]
            else:
                action_value = -1
            action_values.append(action_value)

        new_action = np.argmax(action_values)
        new_pi[i, j] = new_action

        if new_action != old_action:
            policy_stable = False

  return new_pi, policy_stable

# 3- Policy Initialization

In [13]:
def policy_initialization(n):
  """
    This function should return the initial random policy for all states.
  """
  # Define the possible actions (0: 'u', 1: 'r', 2: 'd', 3: 'l')
  actions = [0, 1, 2, 3]
    
  # Initialize a random policy for each state
  pi = np.random.choice(actions, size=(n, n))
    
  return pi

# 4- Policy Iteration algorithm

In [14]:
def policy_iteration(n,Gamma,threshhold):

    pi = policy_initialization(n=n)

    v = np.zeros(shape=(n,n))

    while True:

        v = policy_evaluation(n=n,v=v,pi=pi,threshhold=threshhold,Gamma=Gamma)

        pi , pi_stable = policy_improvement(n=n,pi=pi,v=v,Gamma=Gamma)

        if pi_stable:

            break

    return pi , v

# Main Code to Test

In [19]:
n = 4

Gamma = [0.8,0.9,1]

threshhold = 1e-4

for _gamma in Gamma:
    print("test 1")
    pi , v = policy_iteration(n=n,Gamma=_gamma,threshhold=threshhold)
    print("test 2")
    pi_char = policy_int_to_char(n=n,pi=pi)
    print("test 3")
    print()
    print("Gamma = ",_gamma)

    print()

    print(pi_char)

    print()
    print()

    print(v)


test 1
test 2
test 3

Gamma =  0.8

[['' 'u' 'u' 'u']
 ['l' 'u' 'u' 'r']
 ['l' 'd' 'r' 'r']
 ['d' 'd' 'd' '']]


[[-1.  -1.  -1.  -1. ]
 [-1.  -1.8 -1.8 -1. ]
 [-1.  -1.8 -1.8 -1. ]
 [-1.  -1.  -1.  -1. ]]
test 1
test 2
test 3

Gamma =  0.9

[['' 'u' 'u' 'u']
 ['l' 'u' 'u' 'r']
 ['l' 'd' 'r' 'r']
 ['d' 'd' 'd' '']]


[[-1.  -1.  -1.  -1. ]
 [-1.  -1.9 -1.9 -1. ]
 [-1.  -1.9 -1.9 -1. ]
 [-1.  -1.  -1.  -1. ]]
test 1


KeyboardInterrupt: 